# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f1c41c122cf131554cd9a7a0f4fd5a7c1fc2c3547eba124f606f2aaeed8631d0d9a6bb8a82fa4441ceda37ee690741fe09996dc6f4de330b658989f7527d2579

test:
  secret_key_base: 6356b9f729e108474628a044711e59c3ebaf05bc57127fc65ec0f318f7a4c7b6832a9792a62679137fc1fa8d72b9b9a4aee20185f362c133681c8461c1f68d22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
